-- Password for this user is 'greatwall'
INSERT INTO users 
("username", 
"firstname", 
"lastname",
"email",
"password", 
"salt", 
"role",
"security_question",
"security_answer",
"category1",
"category2",
"neighborhood1",
"neighborhood2") 
VALUES
('userguy412',
'Myron',
'Cope',
'mcope@gmail.com',
'FjZDm+sndmsdEDwNtfr6NA==',
'kidcasB0te7i0jK0fmRIGHSm0mYhdLTaiGkEAiEvLp7dAEHWnuT8n/5bd2V/mqjstQ198iImm1xCmEFu+BHyOz1Mf7vm4LILcrr17y7Ws40Xyx4FOCt8jD03G+jEafpuVJnPiDmaZQXJEpEfekGOvhKGOCtBnT5uatjKEuVWuDA=',
'user',
'What was your dream job as a child?',
'sports announcer',
'sports',
'food',
'northside',
'strip_district'),
('nora',
'nora',
'alwine',
'nora@te.com',
'ak9riD9qE//qr+wgKFHxpA==',
'F0Hj/EtAh1FQqeTRTIciFXTBMgveoKwfyzbM/Ol6VJJiwWRiz5hF+MzvHif/dsBm7zsc8V/CEQrFFotNGnlbZ5o3y99gTdO6Jcm8Da8sjnngFYd4/tpC3WOv15gmziTbNOAsTFeoJjLnqe3bJFsHKFBmpP4RScyiiyK3CgMHUQU=',
'user',
'What was your dream job as a child?',
'sports announcer',
'history',
'',
'oakland',
'')
;

INSERT INTO landmarks
("name",
"category",
"neighborhood",
"address",
"city",
"state",
"zip",
"price",
"weekday_open",
"weekday_close",
"weekend_open",
"weekend_close",
"min_visit_length",
"max_visit_length",
"likes",
"dislikes",
"description",
"image")
VALUES
('Warhol Museum',
'Art',
'Northside',
'117 Sandusky St.',
'Pittsburgh',
'PA',
'15212',
'15',
'600',
'1020',
'600',
'1020',
'1',
'2',
'0',
'0',
'The Andy Warhol Museum is the largest museum in North America dedicated to a single artist. The museum holds an extensive permanent collection of art and archives from the Pittsburgh-born pop art icon Andy Warhol. The Andy Warhol Museum is one of the four Carnegie Museums of Pittsburgh. The main entrance is located on Sandusky Street. Containing 17 galleries, the museum features 900 paintings, close to 2,000 works on paper, over 1,000 published unique prints, 77 sculptures, 4,000 photographs, and over 4,350 Warhol films and videotaped works.',
'../img/1_img.jpg'),
('be Gallery',
'Art',
'Northside',
'3583 Butler St.',
'Pittsburgh',
'PA',
'15220',
'0',
'660',
'1020',
'660',
'1020',
'1',
'2',
'0',
'0',
'Borelli-Edwards was established in 1978, in the North Hills of Pittsburgh, PA, where it evolved into an exhibition space for regional artists and Japanese prints and paintings.  In addition, owner Joy Borelli-Edwards offers the services of fine art appraisals, estate sales, general and archival framing, installations and print and painting restoration.',
'../img/2_img.jpg'),
('Wood Street Galleries',
'Art',
'Downtown',
'601 Wood St.',
'Pittsburgh',
'PA',
'15222',
'0',
'660',
'1020',
'660',
'1020',
'1',
'2',
'0',
'0',
'Wood Street Galleries, a visual arts project of the Pittsburgh Cultural Trust, is a gallery located in Downtown Pittsburgh, Pennsylvania. The gallery occupies the upper floors of the Max Azen company building, above the Wood Street light rail stop.',
'../img/3_img.jpg'),
('The Frick Pittsburgh',
'Art',
'Point Breeze',
'7227 Reynolds St.',
'Pittsburgh',
'PA',
'15208',
'0',
'600',
'960',
'0',
'0',
'1',
'4',
'0',
'0',
'Frick Park is the largest municipal park in Pittsburgh, Pennsylvania, covering 644 acres.',
'../img/4_img.jpg'),
('Carnegie Museum of Art',
'Art',
'Oakland',
'4400 Forbes Ave.',
'Pittsburgh',
'PA',
'15213',
'20',
'600',
'960',
'0',
'0',
'1',
'4',
'0',
'0',
'Carnegie Museum of Art is arguably the first museum of contemporary art in the United States, collecting the “Old Masters of tomorrow” since the inception of the Carnegie International in 1896. Today, the museum is one of the most dynamic major art institutions in America. Our collection of more than 30,000 objects features a broad spectrum of visual arts, including painting and sculpture; prints and drawings; photographs; architectural casts, renderings, and models; decorative arts and design; and film, video, and digital imagery.',
'../img/5_img.jpg'),
('Mattress Factory Museum of Contemporary Art',
'Art',
'Northside',
'500 Sampsonia Way',
'Pittsburgh',
'PA',
'15212',
'20',
'660',
'1020',
'660',
'1020',
'1',
'2',
'0',
'0',
'The Mattress Factory was founded in 1977, by artists, to support artists working in residence to create site-specific installations. Since then, the museum has presented and commissioned new installation and performance works by more than 750 artists.',
'../img/6_img.jpg'),
('The Center for American Music (Stephen Foster Museum)',
'Art',
'Oakland',
'4301 Forbes Ave.',
'Pittsburgh',
'PA',
'15260',
'0',
'600',
'1020',
'600',
'1020',
'1',
'2',
'0',
'0',
'The Stephen Collins Foster Memorial is a performing arts center and museum. It is dedicated to the life and works of American songwriter Stephen Foster.',
'../img/7_img.jpg'),
('SPACE Gallery',
'Art',
'Downtown',
'812 Liberty Ave',
'Pittsburgh',
'PA',
'15222',
'0',
'660',
'1020',
'660',
'1020',
'1',
'2',
'0',
'0',
'The mission of SPACE is to realize a working example of an integrated and open art ecosystem in Pittsburgh. SPACE values the creation of new works in multi-disciplines, presentation of artwork to the broadest possible audience, inclusion of established and contemporary technologies and the promotion of local artists outside of the region.',
'../img/8_img.jpg'),
('Carnegie Museum of Natural History',
'History',
'Oakland',
'4400 Forbes Ave.',
'Pittsburgh',
'PA',
'15213',
'20',
'660',
'1020',
'660',
'1020',
'1',
'2',
'0',
'0',
'Carnegie Museum of Natural History, one of the four Carnegie Museums of Pittsburgh, is among the top natural history museums in the country. It maintains, preserves, and interprets an extraordinary collection of artifacts, objects, and scientific specimens used to broaden understanding of evolution, conservation, and biodiversity. Carnegie Museum of Natural History generates new scientific knowledge, advances science literacy, and inspires visitors of all ages to become passionate about science, nature, and world cultures.',
'../img/9_img.jpg'),
('Soldiers & Sailors Memorial Hall & Museum',
'History',
'Oakland',
'4141 Fifth Ave.',
'Pittsburgh',
'PA',
'15213',
'10',
'600',
'1020',
'600',
'1020',
'1',
'4',
'0',
'0',
'Soldiers and Sailors Memorial Hall and Museum is a National Register of Historic Places landmark in Pittsburgh, Pennsylvania, United States. It is the largest memorial in the United States dedicated solely to honoring all branches of military veterans and service personnel',
'../img/10_img.jpg'),
('Senator John Heinz History Center',
'History',
'Strip District',
'1212 Smallman St.',
'Pittsburgh',
'PA',
'15222',
'15',
'600',
'960',
'720',
'1200',
'1',
'4',
'0',
'0',
'The History Center is an educational institution that engages and inspires large and diverse audiences through programs that enable links to the past, understanding in the present, and guidance for the future by preserving regional history and presenting the American experience with a Western Pennsylvania connection.',
'../img/11_img.jpg'),
('Carrie Furnace',
'History',
'Rankin',
'801 Carrie Furnace Blvd.',
'Homestead',
'PA',
'15120',
'20',
'600',
'900',
'600',
'900',
'1',
'2',
'0',
'0',
'Carrie Furnace is a former blast furnace located along the Monongahela River in the Pittsburgh area industrial town of Swissvale, Pennsylvania, and it had formed a part of the Homestead Steel Works. The Carrie Furnaces were built in 1884 and they operated until 1982.',
'../img/12_img.jpg'),
('Cathedral of Learning Nationality Rooms',
'History',
'Oakland',
'4200 Fifth Ave.',
'Pittsburgh',
'PA',
'15260',
'10',
'540',
'960',
'660',
'960',
'1',
'2',
'0',
'0',
'The Nationality Rooms are a collection of 31 classrooms in the University of Pittsburgh Cathedral of Learning depicting and donated by the national and ethnic groups that helped build the city of Pittsburgh.',
'../img/13_img.jpg'),
('Center for PostNatural History',
'History',
'Garfield',
'4913 Penn Avenue ',
'Pittsburgh',
'PA',
'15224',
'10',
'0',
'600',
'720',
'960',
'1',
'1',
'0',
'0',
'The Center for PostNatural History is a storefront museum in the Garfield neighborhood of Pittsburgh. In contrast to typical natural history museums, it is focused on the collection and exposition of organisms that have been intentionally and heritably altered by humans by means including selective breeding or genetic engineering, a phenomenon referred to as the postnatural.',
'../img/14_img.jpg'),
('USS Requin',
'History',
'Northside',
'One Allegheny Ave',
'Pittsburgh',
'PA',
'15212',
'15',
'660',
'990',
'660',
'990',
'1',
'2',
'0',
'0',
'Commissioned on April 28, 1945, as a Standard Fleet Submarine, Requin made its first journey to Hawaii to join the Pacific Fleet at Balboa. Arriving at Pearl Harbor in early August of the same year, the submarine prepared for its first war patrol. In port at Pearl Harbor Naval Base when World War II ended, Requin departed and headed west for Guam.',
'../img/15_img.jpg'),
('Roslyn Place',
'History',
'Shadyside',
'520 Rosyln Place',
'Pittsburgh',
'PA',
'15232',
'0',
'540',
'1200',
'540',
'1200',
'1',
'2',
'0',
'0',
'Roslyn Place is a Historic Landmark in the Shadyside neighborhood of Pittsburgh,Pennsylvania. It is said to be the last functional wooden street in America and definitely among the very few wooden streets. It is a small residential street made up of wooden bricks. A must see if you are interested in architecture, history, etc.',
'../img/16_img.jpg'),
('Randyland',
'Oddities',
'Northside',
'1507 Arch St.',
'Pittsburgh',
'PA',
'15212',
'0',
'660',
'1020',
'660',
'1020',
'1',
'2',
'0',
'0',
'Randy Gilson bought Randyland on a credit card in 1995. Every day after waiting tables, he came home to paint and bring happiness to his neighborhood. Now people travel all over to share his dream.',
'../img/17_img.jpg'),
('Bicycle Heaven',
'Oddities',
'Manchester',
'1800 Columbus Ave.',
'Pittsburgh',
'PA',
'15233',
'0',
'660',
'1200',
'660',
'1200',
'1',
'2',
'0',
'0',
'Bicycle Heaven is the largest transportation museum in the world dedicated to bicycles. The museum was founded by Craig Morrow and comprises his personal collection gathered over decades. It is located in Pittsburgh, Pennsylvania. The museum is an active collection.',
'../img/18_img.jpg'),
('Photo Antiquities Museum',
'Oddities',
'Northside',
'531 E Ohio St.',
'Pittsburgh',
'PA',
'15212',
'10',
'600',
'1200',
'600',
'1200',
'1',
'2',
'0',
'0',
'Independent store & gallery packed with vintage photographic equipment, offering informative tours.',
'../img/19_img.jpg'),
('Duquesne Incline',
'Oddities',
'Mt.Washington',
'1220 Grandview Avenue',
'Pittsburgh',
'PA',
'15211',
'5',
'360',
'1440',
'420',
'1220',
'1',
'1',
'0',
'0',
'The Duquesne Incline is one of those which follows very closely the tracks of an early coal hoist. Old newspapers indicate the existence of such a conveyance as early as 1854.',
'../img/20_img.jpg'),
('Frick Car & Carriage Museum',
'Oddities',
'Point Breeze',
'7227 Reynolds Street',
'Pittsburgh',
'PA',
'15208',
'0',
'660',
'1020',
'660',
'1020',
'1',
'2',
'0',
'0',
'At the turn of the 20th century, the development of the automobile profoundly changed American life. In the Car and Carriage Museum, visitors can travel back to the time of carriages, see some of the first horseless carriages to have an impact on Pittsburgh, and learn about the role Pittsburgh played in the development of the automobile industry.',
'../img/21_img.jpg'),
('Shark Tombstone of Allegheny Cemetary',
'Oddities',
'Lawrenceville',
'4734 Butler Street',
'Pittsburgh',
'PA',
'15224',
'0',
'660',
'1020',
'660',
'1020',
'1',
'1',
'0',
'0',
'A Korean War Veteran, Lester C. Madden loved the movie Jaws so much that when he died in 1983, he wanted to spend the rest of time buried under its iconic great white shark.',
'../img/22_img.jpg'),
('Jerrys Records',
'Oddities',
'Squirrel Hill',
'2136 Murray Avenue, 2nd Floor',
'Pittsburgh',
'PA',
'15217',
'0',
'660',
'1020',
'660',
'1020',
'1',
'2',
'0',
'0',
'Jerry’s Records, located in the heart of the historic Squirrel Hill neighborhood of Pittsburgh, PA, is home to the world’s finest vinyl at the most affordable prices anywhere. Jerry’s old-fashioned, bricks & mortar, hands-on, fair approach to moving vinyl from people who no longer want it to people who do, has enabled the store to survive. Jerry’s Records is home to half a million albums, 12″ singles, 45s, and EPs. It’s a record lover’s paradise.',
'../img/23_img.jpg'),
('Saint Anthony Chapel',
'Oddities',
'Troy Hill',
'1704 Harpster St',
'Pittsburgh',
'PA',
'15212',
'0',
'840',
'1020',
'840',
'1020',
'1',
'2',
'0',
'0',
'Saint Anthony Chapel is home to the largest collection of publicly venerable Christian relics – 5,000 in total – in the world outside of the Vatican. The chapel and its relics were the personal property of Suitbert Godfrey Mollinger (1828-1892), a Belgian-born noble/physician-turned-priest who gained an international reputation as a source of hope and healing.',
'../img/24_img.jpg'),
('Schenley Park',
'Nature',
'Oakland',
'3898 Boulevard Of The Allies',
'Pittsburgh',
'PA',
'15213',
'0',
'360',
'1440',
'360',
'1440',
'1',
'4',
'0',
'0',
'Schenley Park is a large municipal park located in Pittsburgh, Pennsylvania, between the neighborhoods of Oakland, Greenfield, and Squirrel Hill. It is also listed on the National Register of Historic Places as a historic district.',
'../img/25_img.jpg'),
('Frick Park',
'Nature',
'Oakland',
'1981 Beechwood Blvd',
'Pittsburgh',
'PA',
'15217',
'0',
'360',
'1440',
'360',
'1440',
'1',
'4',
'0',
'0',
'Frick Park is the largest municipal park in Pittsburgh, Pennsylvania, covering 644 acres.',
'../img/26_img.jpg'),
('Phipps Conservatory',
'Nature',
'Squirrel Hill',
'1 Schenley Drive',
'Pittsburgh',
'PA',
'15213',
'15',
'360',
'1440',
'360',
'1440',
'1',
'2',
'0',
'0',
'Phipps Conservatory and Botanical Gardens is a botanical garden set in Schenley Park, Pittsburgh, Pennsylvania, United States. It is a City of Pittsburgh historic landmark and is listed on the National Register of Historic Places.',
'../img/27_img.jpg'),
('National Aviary',
'Nature',
'Northside',
'700 Arch St',
'Pittsburgh',
'PA',
'15212',
'18',
'660',
'1020',
'660',
'1020',
'1',
'2',
'0',
'0',
'The National Aviary, located in Pittsburgh, Pennsylvania, is the only independent indoor nonprofit aviary in the United States.',
'../img/28_img.jpg'),
('Frick Environmental Center',
'Nature',
'Point Breeze',
'2005 Beechwood Blvd',
'Pittsburgh',
'PA',
'15217',
'0',
'660',
'1020',
'720',
'1020',
'1',
'1',
'0',
'0',
'The Frick Environmental Center provides families, students, and learners of all ages with a state-of-the-art space for hands-on, experiential environmental education. The Center serves as the classroom base for programming that extends into the surrounding park woodlands, streams, meadows and trails.',
'../img/29_img.jpg'),
('Allegheny Commons Park',
'Nature',
'Northside',
'810 Arch Street',
'Pittsburgh',
'PA',
'15212',
'0',
'360',
'1200',
'360',
'1200',
'1',
'2',
'0',
'0',
'Allegheny Commons is a municipal park located in the Northside of Pittsburgh. Dating to 1867, it is the oldest park in the city of Pittsburgh.',
'../img/30_img.jpg'),
('Pittsburgh Zoo and PPG Aquarium',
'Nature',
'Highland Park',
'7370 Baker St',
'Pittsburgh',
'PA',
'15206',
'0',
'600',
'1020',
'600',
'1020',
'1',
'2',
'0',
'0',
'The Pittsburgh Zoo is one of only six major zoo and aquarium combinations in the United States. Located in Highland Park area of Pittsburgh, the zoo sits on 77 acres of park land where it exhibits more than 4,000 animals representing 475 species, including 20 threatened or endangered species.',
'../img/31_img.jpg'),
('Point State Park',
'Nature',
'Downtown',
'601 Commonwealth Pl',
'Pittsburgh',
'PA',
'15222',
'0',
'360',
'1200',
'360',
'1200',
'1',
'2',
'0',
'0',
'Point State Park is a Pennsylvania state park on 36 acres in Downtown Pittsburgh, Allegheny County, Pennsylvania, USA, at the confluence of the Allegheny and Monongahela rivers, forming the Ohio River.',
'../img/32_img.jpg'),
('Clark Bar & Grill',
'Food',
'Northside',
'503 Martindale St.',
'Pittsburgh',
'PA',
'15212',
'0',
'720',
'1300',
'0',
'0',
'1',
'4',
'0',
'0',
'Lined with unique and rare sports memorabilia, the Clark Bar & Grill is the ideal setting for lunch, dinner or happy hour. Our restaurant has remained a constant tradition for over 20 years in the ever-evolving city of Pittsburgh.',
'../img/33_img.jpg'),
('DiAnoias',
'Food',
'Strip District',
'2549 Penn Ave.',
'Pittsburgh',
'PA',
'15222',
'0',
'540',
'1200',
'600',
'1300',
'1',
'4',
'0',
'0',
'Family owned Italian restaurant that specializes in homemade pastas, pastries, breads, sandwiches and more. Open for breakfast, lunch and dinner.',
'../img/34_img.jpg'),
('DeLucas Diner',
'Food',
'Strip District',
'2015 Penn Ave.',
'Pittsburgh',
'PA',
'15222',
'0',
'390',
'840',
'390',
'840',
'1',
'4',
'0',
'0',
'Colorful diner space is a draw for waffles, omelets, mini-burgers & other breakfast & lunch items.',
'../img/35_img.jpg'),
('Primantis',
'Food',
'Strip District',
'46 18th St.',
'Pittsburgh',
'PA',
'15222',
'20',
'0',
'1440',
'0',
'1440',
'1',
'2',
'0',
'0',
'The original shop is located at 46 18th Street in the Strip District section of Pittsburgh. The tradition of the signature sandwiches (typically ordered by number based on a menu written on a huge chalkboard behind the counter) was to combine the sandwich and side of fries, held (grilled) together with eggs as a binding unit, straight from the grill into a hoagie bun. The sandwich was then wrapped in a sheet of newspaper and handed to the customer. This was done so the customer could then go back to his (hopefully loaded) truck and drive back to his shop while managing to eat the sandwich while driving without getting it all over his lap.',
'../img/36_img.jpg'),
('The Cafe at the Frick',
'Food',
'Point Breeze',
'7227 Reynolds St',
'Pittsburgh',
'PA',
'15208',
'20',
'660',
'1000',
'660',
'1000',
'1',
'2',
'0',
'0',
'Quaint cottage on the Frick estate with a patio & garden views for choice cafe eats & afternoon tea.',
'../img/37_img.jpg'),
('The Original Hot Dog Shop',
'Food',
'Oakland',
'3901 Forbes Ave',
'Pittsburgh',
'PA',
'15213',
'20',
'600',
'1300',
'600',
'800',
'1',
'1',
'0',
'0',
'This old-school eatery serves franks, burgers, fries & craft beers.',
'../img/38_img.jpg'),
('Biddles Escape',
'Food',
'Regent Square',
'401 Biddle Ave',
'Pittsburgh',
'PA',
'15221',
'10',
'480',
'1000',
'480',
'1000',
'1',
'2',
'0',
'0',
'Artisanal hot and cold coffee drinks and light fare in an offbeat, local art-lined setting.',
'../img/39_img.jpg'),
('Allegheny Sandwich Shoppe',
'Food',
'Northside',
'822 Western Ave',
'Pittsburgh',
'PA',
'15233',
'15',
'540',
'900',
'540',
'900',
'1',
'2',
'0',
'0',
'Easygoing, venerable stop offering breakfast such as eggs plus hearty deli sandwiches & lunch fare.',
'../img/40_img.jpg'),
('PNC Park Statues',
'Sports',
'Northside',
'115 Federal St.',
'Pittsburgh',
'PA',
'15212',
'0',
'600',
'900',
'0',
'0',
'1',
'1',
'0',
'0',
'Statues of Pirate Hall of Famers surround PNC Park. Honus Wagner, Roberto Clemente, Willie Stargell, and Bill Mazeroski have all been immortalized.',
'../img/41_img.jpg'),
('PNC Park',
'Sports',
'Northside',
'115 Federal Street',
'Pittsburgh',
'PA',
'15212',
'0',
'600',
'1200',
'600',
'1200',
'1',
'1',
'0',
'0',
'PNC Park is a baseball park located on the North Shore of Pittsburgh, Pennsylvania. It is the fifth home of the Pittsburgh Pirates.',
'../img/42_img.jpg'),
('Heinz Field',
'Sports',
'Northside',
'100 Art Rooney Drive',
'Pittsburgh',
'PA',
'15212',
'0',
'600',
'1200',
'600',
'1200',
'1',
'1',
'0',
'0',
'Heinz Field is a stadium located in the North Shore neighborhood of Pittsburgh, Pennsylvania, United States. It primarily serves as the home of the Pittsburgh Steelers.',
'../img/43_img.jpg'),
('Consol Energy Center',
'Sports',
'Downtown',
'1001 Fifth Avenue',
'Pittsburgh',
'PA',
'15219',
'0',
'600',
'1200',
'600',
'1200',
'1',
'1',
'0',
'0',
'Consol Energy Center is a multi-purpose indoor arena in Pittsburgh, Pennsylvania that serves as home to the Pittsburgh Penguins of the National Hockey League.',
'../img/44_img.jpg'),
('Roberto Clemente Museum',
'Sports',
'Lawrenceville',
'3339 Penn Avenue',
'Pittsburgh',
'PA',
'15201',
'20',
'600',
'900',
'600',
'900',
'1',
'1',
'0',
'0',
'The Roberto Clemente Museum is an American museum honoring Roberto Clemente, the Major League Baseball right fielder of the Pittsburgh Pirates and Hall of Famer. The museum located in the former Engine House No. 25, in the Lawrenceville section of in Pittsburgh, Pennsylvania.',
'../img/45_img.jpg'),
('The Immaculate Reception Monument',
'Sports',
'Northshore',
'316 North Shore Drive',
'Pittsburgh',
'PA',
'15212',
'0',
'600',
'900',
'600',
'900',
'1',
'1',
'0',
'0',
'Known as the Immaculate Reception, the play is memorialized on the exact spot where it happened, on the site of the old Three Rivers Stadium.',
'../img/46_img.jpg'),
('Forbes Field Outfield Wall',
'Sports',
'Oakland',
'230 South Bouquet Street',
'Pittsburgh',
'PA',
'15213',
'0',
'480',
'1300',
'480',
'1300',
'1',
'2',
'0',
'0',
'Forbes Field was a baseball park in the Oakland neighborhood of Pittsburgh, Pennsylvania, from 1909 to June 28, 1970. It was the third home of the Pittsburgh Pirates Major League Baseball team, and the first home of the Pittsburgh Steelers.',
'../img/47_img.jpg'),
('Petersen Events Center',
'Sports',
'Oakland',
'3719 Terrace Street',
'Pittsburgh',
'PA',
'15261',
'0',
'480',
'1300',
'480',
'1300',
'1',
'3',
'0',
'0',
'The Petersen Events Center is a 12,508-seat multi-purpose arena on the campus of the University of Pittsburgh in the Oakland neighborhood.',
'../img/48_img.jpg')
;

INSERT INTO itinerary 
("user_id",
"home_base",
"date",
"start_time", 
"route", 
"landmark1",
"landmark2",
"landmark3",
"landmark4",
"landmark5",
"landmark6",
"landmark7",
"disabled") 
VALUES
('1',
'Renaissance Pittsburgh Hotel, 107 6th St, Pittsburgh, PA 15222',
'12-20-2019',
'10:00',
'route',
'3',
'6',
'1',
'',
'',
'',
'',
'0')
;